export enum ReportingPointType {
    REQUEST_SENT,
    REQUEST_RECEIVED,
    RESPONSE_SENT,
    RESPONSE_RECEIVED,
    ERROR,
    SERVICE_START,
    SERVICE_STARTED,
    SERVICE_STOP,
    SERVICE_STOPPED,
}
